sudo:  required
dist: trusty
language: node_js
node_js:
- 6.9.5
script:
- PORT=8888 npm start &
- sleep 3
- curl http://localhost:8888
deploy:
  provider: script
  skip_cleanup: true
  script:
    node_modules/.bin/deploy_to_bluemix.sh
  manifest: manifest.yml
  username: rios.mariana
  password: 2doorcinemaClub
  organization: rios.mariana
  space: dev
  on:
    branch: master